<?php
/**
 * Generated by Protobuf protoc plugin.
 * File descriptor : PulsarApi.proto
 */


namespace Pulsar\Proto\CommandSubscribe;

/**
 * Protobuf enum : pulsar.proto.CommandSubscribe.InitialPosition
 */
class InitialPosition extends \Protobuf\Enum
{

    /**
     * Latest = 0
     */
    const Latest_VALUE = 0;

    /**
     * Earliest = 1
     */
    const Earliest_VALUE = 1;

    /**
     * @var \Pulsar\Proto\CommandSubscribe\InitialPosition
     */
    protected static $Latest = null;

    /**
     * @var \Pulsar\Proto\CommandSubscribe\InitialPosition
     */
    protected static $Earliest = null;

    /**
     * @return \Pulsar\Proto\CommandSubscribe\InitialPosition
     */
    public static function Latest()
    {
        if (self::$Latest !== null) {
            return self::$Latest;
        }

        return self::$Latest = new self('Latest', self::Latest_VALUE);
    }

    /**
     * @return \Pulsar\Proto\CommandSubscribe\InitialPosition
     */
    public static function Earliest()
    {
        if (self::$Earliest !== null) {
            return self::$Earliest;
        }

        return self::$Earliest = new self('Earliest', self::Earliest_VALUE);
    }

    /**
     * @param int $value
     * @return \Pulsar\Proto\CommandSubscribe\InitialPosition
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0:
                return self::Latest();
            case 1:
                return self::Earliest();
            default:
                return null;
        }
    }


}

