<?php
/**
 * Generated by Protobuf protoc plugin.
 * File descriptor : PulsarApi.proto
 */


namespace Pulsar\Proto;

/**
 * Protobuf message : pulsar.proto.CommandGetTopicsOfNamespace
 */
class CommandGetTopicsOfNamespace extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * request_id required uint64 = 1
     *
     * @var int
     */
    protected $request_id = null;

    /**
     * namespace required string = 2
     *
     * @var string
     */
    protected $namespace = null;

    /**
     * mode optional enum = 3
     *
     * @var \Pulsar\Proto\CommandGetTopicsOfNamespace\Mode
     */
    protected $mode = null;

    /**
     * topics_pattern optional string = 4
     *
     * @var string
     */
    protected $topics_pattern = null;

    /**
     * topics_hash optional string = 5
     *
     * @var string
     */
    protected $topics_hash = null;

    /**
     * {@inheritdoc}
     */
    public function __construct($stream = null, \Protobuf\Configuration $configuration = null)
    {
        $this->mode = \Pulsar\Proto\CommandGetTopicsOfNamespace\Mode::PERSISTENT();

        parent::__construct($stream, $configuration);
    }

    /**
     * Check if 'request_id' has a value
     *
     * @return bool
     */
    public function hasRequestId()
    {
        return $this->request_id !== null;
    }

    /**
     * Get 'request_id' value
     *
     * @return int
     */
    public function getRequestId()
    {
        return $this->request_id;
    }

    /**
     * Set 'request_id' value
     *
     * @param int $value
     */
    public function setRequestId($value)
    {
        $this->request_id = $value;
    }

    /**
     * Check if 'namespace' has a value
     *
     * @return bool
     */
    public function hasNamespace()
    {
        return $this->namespace !== null;
    }

    /**
     * Get 'namespace' value
     *
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * Set 'namespace' value
     *
     * @param string $value
     */
    public function setNamespace($value)
    {
        $this->namespace = $value;
    }

    /**
     * Check if 'mode' has a value
     *
     * @return bool
     */
    public function hasMode()
    {
        return $this->mode !== null;
    }

    /**
     * Get 'mode' value
     *
     * @return \Pulsar\Proto\CommandGetTopicsOfNamespace\Mode
     */
    public function getMode()
    {
        return $this->mode;
    }

    /**
     * Set 'mode' value
     *
     * @param \Pulsar\Proto\CommandGetTopicsOfNamespace\Mode $value
     */
    public function setMode(\Pulsar\Proto\CommandGetTopicsOfNamespace\Mode $value = null)
    {
        $this->mode = $value;
    }

    /**
     * Check if 'topics_pattern' has a value
     *
     * @return bool
     */
    public function hasTopicsPattern()
    {
        return $this->topics_pattern !== null;
    }

    /**
     * Get 'topics_pattern' value
     *
     * @return string
     */
    public function getTopicsPattern()
    {
        return $this->topics_pattern;
    }

    /**
     * Set 'topics_pattern' value
     *
     * @param string $value
     */
    public function setTopicsPattern($value = null)
    {
        $this->topics_pattern = $value;
    }

    /**
     * Check if 'topics_hash' has a value
     *
     * @return bool
     */
    public function hasTopicsHash()
    {
        return $this->topics_hash !== null;
    }

    /**
     * Get 'topics_hash' value
     *
     * @return string
     */
    public function getTopicsHash()
    {
        return $this->topics_hash;
    }

    /**
     * Set 'topics_hash' value
     *
     * @param string $value
     */
    public function setTopicsHash($value = null)
    {
        $this->topics_hash = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ($this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        if (!isset($values['request_id'])) {
            throw new \InvalidArgumentException('Field "request_id" (tag 1) is required but has no value.');
        }

        if (!isset($values['namespace'])) {
            throw new \InvalidArgumentException('Field "namespace" (tag 2) is required but has no value.');
        }

        $message = new self();
        $values = array_merge([
            'mode'           => \Pulsar\Proto\CommandGetTopicsOfNamespace\Mode::PERSISTENT(),
            'topics_pattern' => null,
            'topics_hash'    => null,
        ], $values);

        $message->setRequestId($values['request_id']);
        $message->setNamespace($values['namespace']);
        $message->setMode($values['mode']);
        $message->setTopicsPattern($values['topics_pattern']);
        $message->setTopicsHash($values['topics_hash']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'  => 'CommandGetTopicsOfNamespace',
            'field' => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name'   => 'request_id',
                    'type'   => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT64(),
                    'label'  => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED(),
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name'   => 'namespace',
                    'type'   => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label'  => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED(),
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number'        => 3,
                    'name'          => 'mode',
                    'type'          => \google\protobuf\FieldDescriptorProto\Type::TYPE_ENUM(),
                    'label'         => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name'     => '.pulsar.proto.CommandGetTopicsOfNamespace.Mode',
                    'default_value' => \Pulsar\Proto\CommandGetTopicsOfNamespace\Mode::PERSISTENT(),
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name'   => 'topics_pattern',
                    'type'   => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label'  => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name'   => 'topics_hash',
                    'type'   => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label'  => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream = $context->getStream();
        $writer = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->request_id === null) {
            throw new \UnexpectedValueException('Field "\\pulsar\\proto\\CommandGetTopicsOfNamespace#request_id" (tag 1) is required but has no value.');
        }

        if ($this->namespace === null) {
            throw new \UnexpectedValueException('Field "\\pulsar\\proto\\CommandGetTopicsOfNamespace#namespace" (tag 2) is required but has no value.');
        }

        if ($this->request_id !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->request_id);
        }

        if ($this->namespace !== null) {
            $writer->writeVarint($stream, 18);
            $writer->writeString($stream, $this->namespace);
        }

        if ($this->mode !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeVarint($stream, $this->mode->value());
        }

        if ($this->topics_pattern !== null) {
            $writer->writeVarint($stream, 34);
            $writer->writeString($stream, $this->topics_pattern);
        }

        if ($this->topics_hash !== null) {
            $writer->writeVarint($stream, 42);
            $writer->writeString($stream, $this->topics_hash);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ( $length !== null )
            ? ( $stream->tell() + $length )
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 4);

                $this->request_id = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->namespace = $reader->readString($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 14);

                $this->mode = \Pulsar\Proto\CommandGetTopicsOfNamespace\Mode::valueOf($reader->readVarint($stream));

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->topics_pattern = $reader->readString($stream);

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->topics_hash = $reader->readString($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size = 0;

        if ($this->request_id !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->request_id);
        }

        if ($this->namespace !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->namespace);
        }

        if ($this->mode !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->mode->value());
        }

        if ($this->topics_pattern !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->topics_pattern);
        }

        if ($this->topics_hash !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->topics_hash);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->request_id = null;
        $this->namespace = null;
        $this->mode = \Pulsar\Proto\CommandGetTopicsOfNamespace\Mode::PERSISTENT();
        $this->topics_pattern = null;
        $this->topics_hash = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if (!$message instanceof \Pulsar\Proto\CommandGetTopicsOfNamespace) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->request_id = ( $message->request_id !== null ) ? $message->request_id : $this->request_id;
        $this->namespace = ( $message->namespace !== null ) ? $message->namespace : $this->namespace;
        $this->mode = ( $message->mode !== null ) ? $message->mode : $this->mode;
        $this->topics_pattern = ( $message->topics_pattern !== null ) ? $message->topics_pattern : $this->topics_pattern;
        $this->topics_hash = ( $message->topics_hash !== null ) ? $message->topics_hash : $this->topics_hash;
    }


}

