<?php
/**
 * Generated by Protobuf protoc plugin.
 * File descriptor : PulsarApi.proto
 */


namespace Pulsar\Proto;

/**
 * Protobuf message : pulsar.proto.CommandGetLastMessageIdResponse
 */
class CommandGetLastMessageIdResponse extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * last_message_id required message = 1
     *
     * @var \Pulsar\Proto\MessageIdData
     */
    protected $last_message_id = null;

    /**
     * request_id required uint64 = 2
     *
     * @var int
     */
    protected $request_id = null;

    /**
     * consumer_mark_delete_position optional message = 3
     *
     * @var \Pulsar\Proto\MessageIdData
     */
    protected $consumer_mark_delete_position = null;

    /**
     * Check if 'last_message_id' has a value
     *
     * @return bool
     */
    public function hasLastMessageId()
    {
        return $this->last_message_id !== null;
    }

    /**
     * Get 'last_message_id' value
     *
     * @return \Pulsar\Proto\MessageIdData
     */
    public function getLastMessageId()
    {
        return $this->last_message_id;
    }

    /**
     * Set 'last_message_id' value
     *
     * @param \Pulsar\Proto\MessageIdData $value
     */
    public function setLastMessageId(\Pulsar\Proto\MessageIdData $value)
    {
        $this->last_message_id = $value;
    }

    /**
     * Check if 'request_id' has a value
     *
     * @return bool
     */
    public function hasRequestId()
    {
        return $this->request_id !== null;
    }

    /**
     * Get 'request_id' value
     *
     * @return int
     */
    public function getRequestId()
    {
        return $this->request_id;
    }

    /**
     * Set 'request_id' value
     *
     * @param int $value
     */
    public function setRequestId($value)
    {
        $this->request_id = $value;
    }

    /**
     * Check if 'consumer_mark_delete_position' has a value
     *
     * @return bool
     */
    public function hasConsumerMarkDeletePosition()
    {
        return $this->consumer_mark_delete_position !== null;
    }

    /**
     * Get 'consumer_mark_delete_position' value
     *
     * @return \Pulsar\Proto\MessageIdData
     */
    public function getConsumerMarkDeletePosition()
    {
        return $this->consumer_mark_delete_position;
    }

    /**
     * Set 'consumer_mark_delete_position' value
     *
     * @param \Pulsar\Proto\MessageIdData $value
     */
    public function setConsumerMarkDeletePosition(?\Pulsar\Proto\MessageIdData $value = null)
    {
        $this->consumer_mark_delete_position = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ($this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, ?\Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        if (!isset($values['last_message_id'])) {
            throw new \InvalidArgumentException('Field "last_message_id" (tag 1) is required but has no value.');
        }

        if (!isset($values['request_id'])) {
            throw new \InvalidArgumentException('Field "request_id" (tag 2) is required but has no value.');
        }

        $message = new self();
        $values = array_merge([
            'consumer_mark_delete_position' => null,
        ], $values);

        $message->setLastMessageId($values['last_message_id']);
        $message->setRequestId($values['request_id']);
        $message->setConsumerMarkDeletePosition($values['consumer_mark_delete_position']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'  => 'CommandGetLastMessageIdResponse',
            'field' => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number'    => 1,
                    'name'      => 'last_message_id',
                    'type'      => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label'     => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED(),
                    'type_name' => '.pulsar.proto.MessageIdData',
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name'   => 'request_id',
                    'type'   => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT64(),
                    'label'  => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED(),
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number'    => 3,
                    'name'      => 'consumer_mark_delete_position',
                    'type'      => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label'     => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.pulsar.proto.MessageIdData',
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(?\Protobuf\Configuration $configuration = null)
    {
        $config = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream = $context->getStream();
        $writer = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->last_message_id === null) {
            throw new \UnexpectedValueException('Field "\\pulsar\\proto\\CommandGetLastMessageIdResponse#last_message_id" (tag 1) is required but has no value.');
        }

        if ($this->request_id === null) {
            throw new \UnexpectedValueException('Field "\\pulsar\\proto\\CommandGetLastMessageIdResponse#request_id" (tag 2) is required but has no value.');
        }

        if ($this->last_message_id !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeVarint($stream, $this->last_message_id->serializedSize($sizeContext));
            $this->last_message_id->writeTo($context);
        }

        if ($this->request_id !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->request_id);
        }

        if ($this->consumer_mark_delete_position !== null) {
            $writer->writeVarint($stream, 26);
            $writer->writeVarint($stream, $this->consumer_mark_delete_position->serializedSize($sizeContext));
            $this->consumer_mark_delete_position->writeTo($context);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ( $length !== null )
            ? ( $stream->tell() + $length )
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize = $reader->readVarint($stream);
                $innerMessage = new \Pulsar\Proto\MessageIdData();

                $this->last_message_id = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 4);

                $this->request_id = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize = $reader->readVarint($stream);
                $innerMessage = new \Pulsar\Proto\MessageIdData();

                $this->consumer_mark_delete_position = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size = 0;

        if ($this->last_message_id !== null) {
            $innerSize = $this->last_message_id->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->request_id !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->request_id);
        }

        if ($this->consumer_mark_delete_position !== null) {
            $innerSize = $this->consumer_mark_delete_position->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->last_message_id = null;
        $this->request_id = null;
        $this->consumer_mark_delete_position = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if (!$message instanceof \Pulsar\Proto\CommandGetLastMessageIdResponse) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->last_message_id = ( $message->last_message_id !== null ) ? $message->last_message_id : $this->last_message_id;
        $this->request_id = ( $message->request_id !== null ) ? $message->request_id : $this->request_id;
        $this->consumer_mark_delete_position = ( $message->consumer_mark_delete_position !== null ) ? $message->consumer_mark_delete_position : $this->consumer_mark_delete_position;
    }


}

