<?php
/**
 * Generated by Protobuf protoc plugin.
 * File descriptor : PulsarApi.proto
 */


namespace Pulsar\Proto\CommandPartitionedTopicMetadataResponse;

/**
 * Protobuf enum : pulsar.proto.CommandPartitionedTopicMetadataResponse.LookupType
 */
class LookupType extends \Protobuf\Enum
{

    /**
     * Success = 0
     */
    const Success_VALUE = 0;

    /**
     * Failed = 1
     */
    const Failed_VALUE = 1;

    /**
     * @var \Pulsar\Proto\CommandPartitionedTopicMetadataResponse\LookupType
     */
    protected static $Success = null;

    /**
     * @var \Pulsar\Proto\CommandPartitionedTopicMetadataResponse\LookupType
     */
    protected static $Failed = null;

    /**
     * @return \Pulsar\Proto\CommandPartitionedTopicMetadataResponse\LookupType
     */
    public static function Success()
    {
        if (self::$Success !== null) {
            return self::$Success;
        }

        return self::$Success = new self('Success', self::Success_VALUE);
    }

    /**
     * @return \Pulsar\Proto\CommandPartitionedTopicMetadataResponse\LookupType
     */
    public static function Failed()
    {
        if (self::$Failed !== null) {
            return self::$Failed;
        }

        return self::$Failed = new self('Failed', self::Failed_VALUE);
    }

    /**
     * @param int $value
     * @return \Pulsar\Proto\CommandPartitionedTopicMetadataResponse\LookupType
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0:
                return self::Success();
            case 1:
                return self::Failed();
            default:
                return null;
        }
    }


}

